[package]
name = "graphviz-dot-parser"
version = "0.1.0"
authors = ["Fangyi Zhou <me@fangyi.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
petgraph = "0.5.1"
nom = "6"
